### ISSUE TITLE
Fatal error reading PNG image file: Missing PLTE before IDAT

### ISSUE THREAD

**Issue by bannsec** [eight04/pyAPNG#1]
I read in an image, and print out it's frames (as in your example). All output files have that error.

**Comment by eight04** [comment]
Is the error gave by an image viewer?

**Comment by bannsec** [comment]
Yep. Given by the "eog" command in Ubuntu.

**Comment by eight04** [comment]
Could you upload the original image?

**Comment by eight04** [comment]
http://www.libpng.org/pub/png/spec/1.2/PNG-Chunks.html#C.PLTE

Sometimes PLTE is required. I think some headers should be copied into each frame.

**Comment by eight04** [comment]
Should be fixed in 0.2.0.
