### ISSUE TITLE
Installed apng, but it seems to be empty

### ISSUE THREAD

**Issue by onzie9** [eight04/pyAPNG#11]
I've had the same results with Python 2.7 and 3.6.  
>import apng
>method_list = [func for func in dir(apng) if callable(getattr(apng, func))]
>print(method_list)
>[]

Specifically,
>from apng import APNG
"Cannot find reference 'APNG' in apng.py."

Maybe I am missing a dependency?  I installed apng from the terminal for 3.6 and using the GUI in PyCharm for 2.7.

**Comment by eight04** [comment]
Print the location of the module and check if something went wrong:
```python
import apng
print(apng.__file__)
```

**Comment by onzie9** [comment]
I'm an idiot.  I had my file named the same as the package.  It works perfectly now.
