### ISSUE TITLE
PNG Frame Extract Weirdness

### ISSUE THREAD

**Issue by bannsec** [eight04/pyAPNG#15]
Been banging my head on writing an apng extraction myself. It somewhat works, but I run into issues with this file. Looks like your method runs into issues too..

The file was manually edited by the author to set the number of frames to 1. The technique of looking at the chunks themselves obviously gets by that. However, many of the images that get pulled out are corrupt.

My knowledge of PNG isn't the greatest, so I'm not sure if they're corrupt due to some process error in extracting or if they started that way... Either way, both of our extraction approaches cause some of the output files to be errored.

![p1ng](https://user-images.githubusercontent.com/7632864/52983178-e1182b00-33b7-11e9-9a85-267e02c9516f.png)

**Comment by eight04** [comment]
I think this file contains broken frames. Have you successfully extracted all frames within other tools?

**Comment by bannsec** [comment]
P4 claims to have done it with their own php

https://github.com/p4-team/ctf/blob/master/2016-09-09-asis-final/p1ng/README.md

**Comment by eight04** [comment]
The decoding process in your link is not correct. They ignore the image width/height given by the APNG frame.

You can change the width/height of each frame manually by using some tools like [tweakpng](http://entropymine.com/jason/tweakpng/). After fixing each frame's width/height, you should get an identical result.

Here is a python version that will divide width/height by 10 when they are too large:
```python
import struct
from apng import APNG, make_chunk

im = APNG.open("w.png")
i = 0
first_png = im.frames[0][0]
first_hdr = first_png.chunks[0][1]
for png, ctrl in im.frames:
    # fix header
    width = png.width
    if png.width == 1280:
        width = first_png.width
    elif png.width >= 1000:
        width = png.width // 10
        
    height = png.height
    if png.height == 768:
        height = first_png.height
    elif png.height >= 100:
        height = png.height // 10
        
    chunk_data = make_chunk("IHDR", struct.pack("!II", width, height) + first_hdr[16:-4])
    
    png.chunks[0] = ("IHDR", chunk_data)
    
    png.save("{}.png".format(i))
    i += 1
```
