### ISSUE TITLE
Add `pyAPNG` to Conda Forge

### ISSUE THREAD

**Issue by RoyiAvital** [eight04/pyAPNG#20]
Hi,

Any chance to make `pyAPNG` available on Conda Forge?

**Comment by eight04** [comment]
I have no experience with Conda but I can take a look if there are some instructions.

**Comment by RoyiAvital** [comment]
I have found this: https://blog.gishub.org/how-to-publish-a-python-package-on-conda-forge.

This is the official guide: https://conda-forge.org/docs/maintainer/adding_pkgs.html.

I have never done on my own, but in previous cases I asked, the maintainers got it pretty quickly.
So probably it shouldn't be too much work.

**Comment by eight04** [comment]
https://github.com/conda-forge/staged-recipes/pull/24180

**Comment by eight04** [comment]
Done

**Comment by RoyiAvital** [comment]
Indeed: https://anaconda.org/conda-forge/apng.

Appreciate this :-).
