### ISSUE TITLE
Pass repeat count by argument

### ISSUE THREAD

**Issue by borisdering** [eight04/pyAPNG#4]
Is it possible to pass a repeat count to the apng file? At the moment the repeat count stands at "-1" for repeat forever? Does the specification for apng even support repeat count?

**Comment by eight04** [comment]
Yes, you can specify repeat count in APNG. In this library, the repeat count is always 0 (infinite):
https://github.com/eight04/pyAPNG/blob/aeb6973c5c021a8284c4b4fd650fbfbe4f1c14d4/apng/__init__.py#L261
And it is ignored when reading frames from an APNG file:
https://github.com/eight04/pyAPNG/blob/aeb6973c5c021a8284c4b4fd650fbfbe4f1c14d4/apng/__init__.py#L347-L348
I think we should expose it as a public property `num_plays` of `APNG` instance.

**Comment by borisdering** [comment]
Wow! thank you for the very fast reply. The way to pass this argument would be amazing and would solve my issue. Anyways, how should we move on? I'm pretty new to python and especially to APNG. Should I make the changes or would you like to go ahead?

**Comment by eight04** [comment]
PRs welcome. I would expect something like:
```python
im = APNG.from_files(some_files)
assert im.num_plays == 0
im.num_plays = 5
im.save(result_file) # the result animation should only repeat 5 times

im = APNG.open(result_file)
assert im.num_plays == 5
```

**Comment by ghost** [comment]
pyAPNG works great, and I do like it a lot. 

Regarding #4, could you add a code example to the documtation, how an infinite repeat as well as only-play-once of the animation should be written? Thanks in advance!

**Comment by eight04** [comment]
[`APNG` object has a `num_plays` property](https://pyapng.readthedocs.io/en/latest/#apng.APNG). You can modify this property before writing APNG to file.
